### ISSUE TITLE
你好，我也在做深度估计相关的工作，使用opencv进行双目相机标定存在一些问题

### ISSUE THREAD

**Issue by WilliamOChai** [DIYer22/calibrating#4]
我在使用opencv的calibrateCamera完成之后，然后用它的stereoCalibrate，最后得到的极线校正结果比较奇怪，请问可以想你请教一下吗？

**Comment by DIYer22** [comment]
用的是 calibrating 吗? 我只对使用 calibrating 中遇到的 bug 做有限的支持

**Comment by DIYer22** [comment]
你可以先用 calibrating 跑一下看看有没有问题.

**Comment by WilliamOChai** [comment]
好的，谢谢，我测试了你的数据，能够运行，但是如果只有双目图像，没有深度图，如何使用呢

**Comment by DIYer22** [comment]
@WilliamOChai  深度图只是交叉验证标定的效果用的, 把深度图相关的验证代码注释掉就可以了
